FROM mysql:latest

# Set environment variables
ENV MYSQL_DATABASE students_db

# Copy custom scripts or configuration files from your host to the container
COPY ./scripts/ /docker-entrypoint-initdb.d/
